### ISSUE TITLE
0.4.0 version isn't published

### ISSUE THREAD

**Issue by kistanovdev** [GamePad64/tunio#79]
When I build my project, Cargo is complaning that the package isn't available. 
```toml
[dependencies]
etherparse = "0.13.0"
tunio = "0.4.0"
```
However, when I use 0.3.0 version, I get a compilation error.

My solution was to clone your repo locally and reference it directly and it worked.

```toml
[dependencies]
etherparse = "0.13.0"
tunio = { path = "/Users/kistanov/github/tunio" }
```

Do you need help publishing the 0.4.0 version? Thank you
